### DISCUSSION TITLE
How to disable NGINX Error page and show only the backend application error page instead?

### DISCUSSION THREAD

**Discussion by Tam1020** [nginx/nginx#138] [Q&A]
We have an Authentication/Authorization application hosted in Container (kubernetes) platform with NGINX as Ingress. We have noticed that when the backend application is hitting errors like error codes 502, 504 500, the NGINX error page is shown and not the customized backend application error page.

Below is the YAML definition we have in our environment. 
Kindly advise what is missing to ensure only the backend application error page will appear whenever there is an error on their side. It should not be the NGINX error page will appear. Please advise how to disable the NGINX error page to show. We want the backend application to appear only.

------------------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: isvawrp-proxy
  namespace: isva-iseal
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/ingress.allow-http: "false"
    nginx.org/hsts-max-age: "31536000"
    nginx.ingress.kubernetes.io/custom-http-errors: "409"

------------------------------------------

**Comment by Shriharsh-Deshmukh** [comment]
**Here's what you need to do:**

1. **Add custom error handling for specific HTTP status codes**:
   Update the `nginx.ingress.kubernetes.io/custom-http-errors` annotation to include the desired error codes (502, 504, 500).

   ```yaml
   nginx.ingress.kubernetes.io/custom-http-errors: "502,504,500"
   ```

2. **Specify a custom error page for these errors**:
   You also need to configure your NGINX to route these errors to a specific backend that serves your custom error page. You can either update your existing backend application to handle these errors or specify a custom error page service.

Here’s an updated version of your YAML file:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: isvawrp-proxy
  namespace: isva-iseal
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/ingress.allow-http: "false"
    nginx.org/hsts-max-age: "31536000"
    nginx.ingress.kubernetes.io/custom-http-errors: "502,504,500"
```

Make sure your backend application handles the error responses (502, 504, 500) to show the desired custom error page. If necessary, you can define a separate service in Kubernetes specifically for error handling.
