### DISCUSSION TITLE
nginx and js / css - error 404 / (2: No such file or directory)

### DISCUSSION THREAD

**Discussion by caracola487** [nginx/nginx#535] [General]
Hey fellas,

I  already found a lot of topics for my issue. But unfortunately nothing helped so far. I am pretty unexperienced in using NGINX thus I guess this is a classic newbe misstake. At the moment I am not able to load files from sources like js or css. My setup is pretty easy I guess:

docker-compose.yaml

```
services:
    nginx:
        build:
            dockerfile: ./nginx/dockerfile
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./media:/data/media
            - ./nginx/logs:/var/log/nginx

    php:
        build:
            dockerfile: ./php/dockerfile
        volumes:
            - ./www/html:/var/www/html
            - ./media:/data/media
            - ./sqlite3:/var/lib/sqlite3/data
```

The NGINX dockerfile only contains "FROM nginx:alpine" 

PHP dockerfile:
```
FROM php:8.4-fpm-alpine3.20

#RUN docker-php-ext-install pdo pdo_sqlite

RUN mkdir /data
RUN mkdir /data/media

#RUN chmod -R +x /var/www
RUN chown -R www-data:www-data /data
#RUN chown -R www-data:www-data /var/www/html/css
#RUN chown -R www-data:www-data /var/www/html/inc

USER www-data
```

default.conf:
```
server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php index.html;

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param REQUEST_METHOD $request_method;
        fastcgi_param  SCRIPT_FILENAME $document_root/$fastcgi_script_name;
        include fastcgi_params;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
    
#    location ~ /\.ht {
#        deny  all;
#    }
    location /media/ {
        mp4;
        root /data;
        mp4_buffer_size       4m;
        mp4_max_buffer_size   10m;
    }

    location ~* \.(js|jpg|png)$ {
        root /var/www/html/inc;
        expires 30d;
    }
}
```
In the last days I tried several location set ups.

The directory structure within php container:
home/data/media
home/var/www/html/css
home/var/www/html/inc

The call in html:
```
<!DOCTYPE html>
<html lang="de">
  <header>
    <title>Loginscript</title>
    <link href="../css/style.css" rel="stylesheet">
    <script src="../jquery-3.7.1.min.js"></script>
    <script src="../table.js"></script>
    <script src="../dropdown.js"></script>
  </header>
  <?php
  $feedbackmessage = "";
  ?>
```

That's all my input. Last week I had some issues with mp4 files which are stored in /data/media. In this case I had a permission issue which could be fixed with chown. Now I am getting the same errors for my js and css file calls.
NGINX error log tells me:
```
2025/02/20 12:59:57 [error] 30#30: *4 open() "/var/www/html/inc/css/style.css" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /css/style.css HTTP/1.1", host: "localhost", referrer: "http://localhost/playback.php"
2025/02/20 12:59:57 [error] 31#31: *5 open() "/var/www/html/inc/jquery-3.7.1.min.js" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /jquery-3.7.1.min.js HTTP/1.1", host: "localhost", referrer: "http://localhost/playback.php"
2025/02/20 12:59:57 [error] 30#30: *4 open() "/var/www/html/inc/table.js" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /table.js HTTP/1.1", host: "localhost", referrer: "http://localhost/playback.php"
2025/02/20 12:59:57 [error] 31#31: *5 open() "/var/www/html/inc/dropdown.js" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /dropdown.js HTTP/1.1", host: "localhost", referrer: "http://localhost/playback.php"
```

The PHP Container tells me that the files exists:
```
/var/www/html $ ls -l inc
total 148
-rwxrwxr-x    1 www-data www-data       569 Feb 14 10:47 config.inc.php
-rwxrwxr-x    1 www-data www-data      1167 Feb 19 19:51 dropdown.js
-rwxrwxr-x    1 www-data www-data      4990 Feb 13 11:09 functions.inc.php
-rwxrwxr-x    1 www-data www-data     87533 Feb 19 20:10 jquery-3.7.1.min.js
-rwxrwxr-x    1 www-data www-data     12646 Sep 30  2019 password.inc.php
-rwxrwxr-x    1 www-data www-data      1485 Feb 19 19:35 table.js
/var/www/html $ ls -l css
total 24
-rwxrwxr-x    1 www-data www-data      1500 Feb  7 10:43 style.css
```
Thus I think that my NGINX configuration is wrong. Have one of you an idea what is going wrong? Your help is highly appreciated.
