### ISSUE TITLE
Stream's server_name not taking in regex capture

### ISSUE THREAD

**Issue by brian-bk** [nginx/nginx#132]
### Environment

I'm trying everything in a docker-compose environment to keep things simple and repeatable. I've tried this with nginx=1.25.5 and newer.

<details>

<summary>docker-compose.yaml</summary>

```
services:
  nginx:
    platform: linux/amd64
    image: "nginx:1.25.5-bookworm"
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "33306:33306"
      - "8080:80"
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
  mysql:
    platform: linux/amd64
    image: "mysql:8.0.39-bookworm"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'
```

</details>

<details>

<summary>nginx.conf</summary>

```
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  512;
}




http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    # include /etc/nginx/conf.d/*.conf;

}

stream {
    server {
        listen 33306;

        server_name ~^(?<service>.+).local.docker$;

        proxy_pass $service:3306;
    }
}

```

</details>

<details>

<summary>/etc/hosts</summary>

```
127.0.0.1 mysql.local.docker
```

</details>

### Description

The [`server_name` being added to the streams module](https://nginx.org/en/docs/stream/ngx_stream_core_module.html#server_name), I'm very interested in using it to create a rudimentary dynamic proxy to containerized databases for development environments. However, the regex capture as described in the documentation is not working for me. Perhaps I'm missing some more context about how this is supposed to work, and it might not actually work. 🤷 

When I make a request using telnet, mysql, or curl to `mysql.local.docker` to the stream port 33306, I'm expecting the regex `server_name ~^(?<service>.+).local.docker$;` to capture the host and route the service to `mysql`, and I don't see that happening. The connection is not passed through.

#### nginx configuration

The relevant nginx configuration:
```
stream {
    server {
        listen 33306;

        server_name ~^(?<service>.+).local.docker$;

        proxy_pass $service:3306;
    }
}
```

#### nginx debug log

I can see no `$service` is captured here when I execute `telnet mysql.local.docker 33306`. It ends up being the blank string.

```
nginx-1  | 2024/09/06 22:00:52 [error] 29#29: *1 no host in upstream ":3306", client: 192.168.65.1, server: 0.0.0.0:33306, bytes from/to client:0/0, bytes from/to upstream:0/0
``` 

#### other things

I've tried a few different kind of regex captures, the numbered capture or even a complete capture
```
        server_name ~^(.+)$;
        proxy_pass $1:3306;
```

with no luck.
