### ISSUE TITLE
Configuring nginx as reverse proxy to accept TCP traffic from localhost only

### ISSUE THREAD

**Issue by TryingToCodeSomething** [nginx/nginx#582]
Hi, I am trying to configure nginx as reverse proxy so that it can re-direct call to a nats-server container running in user-defined bridge network. Nginx itself is running in same user-defined network as destination container. The request is originating from another source-container running on same host but in docker host-network. Following is my nginx.conf:

```
# Define the stream block to handle raw TCP traffic
stream {
    server {
        listen 4223;  # NGINX will listen on port 4223 for incoming TCP connections

        # Allow only localhost to connect
        allow 127.0.0.1;  # Only allow requests from localhost
        deny all;  # Deny all other connections

        # Proxy the connection to the NATS server
        proxy_pass nats-server:4222;  # Forward the connection to the NATS server
        proxy_timeout 1m;  # Timeout settings (adjust as needed)
        proxy_connect_timeout 30s;  # Timeout for establishing a connection
    }
}
```

the source-container requests to connect to nats-server via nginx using following configuration:

```
services:
  source-container:
    image: "source-container:latest"
    read_only: true
    network_mode: "host"
    environment:
      - NATS_URL=nats://127.0.0.1:34223
    depends_on:
      - reverse-proxy
  reverse-proxy:
    image: "nginx-latest"
    read_only: true
    ports:
      - 38080:80
      - 34223:4223
    volumes:
      - nginx-cache:/var/cache/nginx
      - nginx-temp:/tmp/nginx
      - nginx-conf:/etc/nginx/
      - nginx-run:/run
  nats-server:
    image: "nats:latest"
    read_only: true
    volumes:
      - temp_data:/tmp
```

When source-container sends request to connect to nats via nginx then I am getting following error:

*1 access forbidden by rule while initializing session, client: 172.19.0.1, server: 0.0.0.0:4223

client: 172.19.0.1 is the IP of getaway of user-defined network in which nats and nginx are running. How do I ensure that nginx only accepts connection request coming from localhost only and does not allow any other entity to be able to connect to nats from outside. I can also do this by exposing nats ports as follows:

```
ports:
      - 127.0.0.1:34223:4222
```

and it would ensure that port 34223 is not open to public network and source-container can also connect to nats. But for some reasons, this configuration does not work in customized deployment environment and hence I cannot use it.

I need help in doing the same via nginx.
